### ISSUE TITLE
Firefox vs Chrome code branches, which one?

### ISSUE THREAD

**Issue by diegogurpegui** [fiatjaf/nos2x#18]
From what I see on the repo, it seems that there is a branch for Chrome Add-on and another one for Firefox Add-on. Is that the case?
I'm not so sure because in the Firefox marketplace the version is 1.4.0, but in the firefox branch it's 1.3.3.

Also, since most of the files are shared, is there a reason why there isn't only 1 branch and each addon on separate folders (with commons files or something)?

**Comment by fiatjaf** [comment]
The reason is that Firefox uses manifest v2 and Chrome uses manifest v3 because our lovely browser overlords can agree about everything except about using the same format for their extensions.

**Comment by fiatjaf** [comment]
The Firefox branch is basically abandoned since I stopped using Firefox myself, so if you're thinking of reviving it I recommend that you take the code and put it on a separate repository and make a new extension according to your own preference, that will probably be better for me, you, the Nostr ecosystem and everyone else.

**Comment by diegogurpegui** [comment]
Got it, thanks for clarifying!

**Comment by diegogurpegui** [comment]
Just so you (and everyone else) know, I already published the Firefox fork of this add-on. I implemented the new UI design (or at least part of it).

Repo: https://github.com/diegogurpegui/nos2x-fox
Page: https://diegogurpegui.com/nos2x-fox/

Thanks!

**Comment by fiatjaf** [comment]
Added it to the README and also to the NIP-07 README.
